## Service
apiVersion: v1
kind: Service
metadata:
  name: etcd-1-accsess
  labels:
    app: etcd-1-accsess
spec:
  type: NodePort
  ports:
  - name: client
    port: 2379
    nodePort: 32379
    targetPort: 2379
  selector:
    app: etcd-1