## PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    app: mysql             #设置 pv 的 label 标签
    type: local
spec:
  storageClassName: manual-mysql
  capacity:          
    storage: 1Gi           #设置 pv 存储资源大小 
  accessModes:       
  - ReadWriteOnce   
  hostPath:  
    path: /Users/office/data/k8s/mysql/data
  persistentVolumeReclaimPolicy: Retain  

---
## PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
spec:
  storageClassName: manual-mysql
  resources:
    requests:
      storage: 1Gi         #设置 pvc 存储资源大小
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: mysql           #根据 Label 选择对应 PV