## Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-accsess
  labels:
    app: mysql-accsess
spec:
  type: NodePort
  ports:
  - name: client
    port: 3306
    nodePort: 30306
    targetPort: 3306
  selector:
    app: mysql